#!/usr/bin/env python

"""
Count length of sequences we pulled out
"""
import sys
infile = open(sys.argv[1])

for line in infile:
    fields = line.rstrip("\r\n").split("\t")
    if int(fields[1]) - int(fields[0]) < 10292:
        continue
    else:

        print ">" + fields[2]
        print fields[3]



        